### ISSUE TITLE
deprecate auto URL formatters for info, zip, icon

### ISSUE THREAD

**Issue by gferreira** [robofont-mechanic/mechanic-2#25]
the GitLab API changed some time ago, so the [current automatic URLs for GitLab-hosted extensions](https://github.com/robofont-mechanic/mechanic-2/blob/bdaabe5473f3eadb1e13a8f138657765779f00d3/Mechanic2.roboFontExt/lib/mechanic2/extensionItem.py#L355-L357) stopped working:

```python
gitlab=dict(
    zipPath="https://gitlab.com{repositoryPath}/-/archive/master/{repositoryName}-master.zip",
    infoPlistPath="https://gitlab.com{repositoryPath}/raw/master/{extensionPath}/info.plist"
),
```

here’s an example of the new API:

```yaml
infoPath: https://gitlab.com/api/v4/projects/15840327/repository/files/RoboFontMarkTool.roboFontExt%2Finfo.plist/raw?ref=master
zipPath: https://gitlab.com/api/v4/projects/15840327/repository/archive.zip?sha=master
icon: https://gitlab.com/api/v4/projects/15840327/repository/files/robofontMarkToolExtensionMechanicIcon.png/raw?ref=master
```

this also works, with user name and repository instead of project ID:

```yaml
icon: https://gitlab.com/api/v4/projects/typoman%2Frobofont-mark-tool/repository/files/robofontMarkToolExtensionMechanicIcon.png/raw?ref=master
```
